version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-docker
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./produtos.sql:/docker-entrypoint-initdb.d/produtos.sql
    networks:
      - postgres-docker

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: yuri@gmail.com
      PGADMIN_DEFAULT_PASSWORD: yuri
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres-docker

networks:
  postgres-docker:
    name: postgres-docker

  